### ISSUE TITLE
Sync option not showing inside drive

### ISSUE THREAD

**Issue by jackjeevan** [JDRIVO/plugin.video.gdrive#8]
In version 2.0.1, not able to sync 'starred' and 'Shared With Me' folders after long press
Please fix

**Comment by JDRIVO** [comment]
@jackjeevan that's never been possible. You have to access each respective folder and sync the "child" folders individually. Although I could look into adding a "Sync all" option in the cotext menu for the mentioned folders that will sync every folder within them.

**Comment by JDRIVO** [comment]
@jackjeevan check out the lastest master build. I have added "Sync multiple" and "Sync all" options to the context menu.  Long press on a folder after entering the "starred" folder for example.
